server:
  port: 8090
spring:
  datasource:
    username: root
    password: wodediannao
    url: jdbc:mysql://192.168.137.138/exam
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"